version: '2.3.3'

services:
  # MySQL database service

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stationski
    ports:
      - "3307:3307"

    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml:ro
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  app:

    image: myapp
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""


volumes:
  mysql-data:

networks:
  mynetwork: