version: '3'

services:
  app:
    image: station-ski-image
    restart: on-failure 
    ports:
      - "8089:8089" 
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always   
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: oussamabadri
      MYSQL_USER: oussamabadri
      MYSQL_PASSWORD: oussamabadri
    volumes:
      - db-data:/var/lib/mysql


volumes:
  db-data:
