version: '2.3.3'

services:
  # MySQL database service
  mysqldb:
    image: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: stationski
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:



volumes:
  mysql-data:

